config/routes.rb
Rails.application.routes.draw do

  devise_for :users  
 
  root 'contacts#index'
  
  resources :users
  resources :contacts
 
end

app/models/contact.rb
load 'lib/validators.rb' # Custom validator

class Contact < ActiveRecord::Base
  include Validators # Include a custom lib to validate email format
  
  belongs_to :user
  
  # Validate uniqueness of email for a new contact
  validates_uniqueness_of :email, :scope => :user_id
  
  # Validate presence of last_name and first_name in a new contact registration
  validates :first_name, :last_name, presence: true 
  
  # Validate presence and format of email field for a new contact registration
  validates :email, :email => true, presence: true
             
  # Avatar file handler
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: ":id_identicon.png"
     validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  
  # After save contact callback
  after_save :create_identicon
  
  # Define a scope to get contacts for only one user
  scope :filter_by_user, -> (user) {where("user_id = ?", user.id)}
  
  # Preformat name for to_s calls
  def name
    "#{self.first_name} #{self.last_name}"
  end
  alias to_s name
  
  # Crate an identicon for each contact created
  def create_identicon 
    RubyIdenticon.create_and_save("#{self.name}", "app/assets/images/#{self.id}_identicon.png")
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  # Include default devise modules. 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :contacts
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  before_action :authenticate_user! # Validate user authentication
  
  respond_to :html, :js
  
  # Main Action
  def index
    @contacts = Contact.order(:last_name).filter_by_user(current_user)
    @query = "#{params[:query]}%"
    @contacts = @contacts.where("first_name LIKE ? OR last_name LIKE ? OR address LIKE ? OR phone LIKE ? OR email LIKE ?", 
                                 @query, @query, @query, @query, @query) if params[:query] != nil
  end

  # New contact method
  def new
    @contact = Contact.new
  end
  
  # New callback method
  def create
    contact = Contact.new(contact_params)
    if contact.save
      @contacts = Contact.order(:last_name).filter_by_user(current_user)
    else
      @contact = contact
    end
  end

  # Edit contact method
  def edit
    @contact = Contact.find(params[:id])
  end
  
  # Remove contact method
  def destroy
    contact = Contact.find(params[:id])
    contact.destroy!
    @contacts = Contact.order(:last_name).filter_by_user(current_user)
  end
  
  # Edit callback method
  def update
    contact = Contact.find(params[:id])
    if contact.update_attributes(contact_params)
      @contacts = Contact.order(:last_name).filter_by_user(current_user)
    else
      @contact = contact
    end
  end
  
  # Strong parameters section
  private
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :avatar, :address, :phone, :email, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.haml
.modal-dialog
  .modal-content
    .modal-header
      %button(type="button" class="close" data-dismiss="modal" aria-label="Close") 
      %h4(class="modal-title")Modal title  
    .modal-body
      #contact-form
        = simple_form_for(@contact, remote: true, html: { class: 'form-horizontal' }) do |f|
          %fieldset
            = f.input :first_name
            = f.input :last_name
            = f.input :email
            = f.input :address
            = f.input :phone
            = f.input :avatar
            = f.input :user_id, as: :hidden, input_html: {value: "#{current_user.id}"} 
            = f.button :submit

app/views/contacts/_grid.haml
.row
  .col-md-12
    .message
      - if @query != "%"
        %p= "#{pluralize(@contacts.count, 'contact')} founded, Query: #{@query}"
        %a{href: "#{contacts_path}", class: "btn btn-default"}(data-remote="true") Reset Query
.row
  .col-md-12

    #masonry-container.transitions-enabled.infinite-scroll.clearfix.centered
      - @contacts.each do |contact|
        %div{class: "box col3", first_name: "l_#{contact.first_name}", last_name: "l_#{contact.last_name}"}
          .row.contact
            .col-md-4.image-contact
              =image_tag(contact.avatar)
            .col-md-8.detail-contact
              %span.options 
                %a.btn.btn-danger.btn-xs{href: "#{contact_path(contact.id)}"}(data-remote="true" data-method='delete' data-confirm="Are you sure to delete this contact?")
                  %span.glyphicon.glyphicon-remove(aria-hidden="true")
                %a.btn.btn-info.btn-xs{href: "#{edit_contact_path(contact.id)}"}(data-remote="true")
                  %span.glyphicon.glyphicon-pencil(aria-hidden="true")
              %h4
                = contact.name
            
              %h5= contact.email
              %p= contact.address
              %p= contact.phone
          
            
    #no-filtered.transitions-enabled.infinite-scroll.clearfix.centered

 

app/views/contacts/create.js.erb
<% if @contact != nil %>
  <% p @contact.inspect %>
  $('#contact_form_modal').html("<%= j (render 'form') %>");
<% else %>
  $('#contact_form_modal').modal('hide');
  $('#grid').html("<%= j (render 'grid') %>");
  
  $('#masonry-container').masonry({
    itemSelector: '.box',
    isAnimated: !Modernizr.csstransitions, 
    columnWidth: function( containerWidth ) {
      return containerWidth / 6;
    }
  }); 
  
<% end %>

app/views/contacts/destroy.js.erb
$('#contact_form_modal').modal('hide');
$('#grid').html("<%= j (render 'grid') %>");

$('#masonry-container').masonry({
  itemSelector: '.box',
  isAnimated: !Modernizr.csstransitions, 
  columnWidth: function( containerWidth ) {
    return containerWidth / 6;
  }
}); 

app/views/contacts/edit.js.erb
$('#contact_form_modal').modal();
$('#contact_form_modal').html("<%= j (render 'form') %>");

app/views/contacts/index.html.haml
.row
  .col-md-12
    .alphabet-menu
      %a.letter_item{href: "#", letter: ""} All
      %a.letter_item{href: "#", letter: "A"} A
      %a.letter_item{href: "#", letter: "B"} B
      %a.letter_item{href: "#", letter: "C"} C
      %a.letter_item{href: "#", letter: "D"} D
      %a.letter_item{href: "#", letter: "E"} E
      %a.letter_item{href: "#", letter: "F"} F
      %a.letter_item{href: "#", letter: "G"} G
      %a.letter_item{href: "#", letter: "H"} H
      %a.letter_item{href: "#", letter: "I"} I
      %a.letter_item{href: "#", letter: "J"} J
      %a.letter_item{href: "#", letter: "K"} K
      %a.letter_item{href: "#", letter: "L"} L
      %a.letter_item{href: "#", letter: "M"} M
      %a.letter_item{href: "#", letter: "N"} N
      %a.letter_item{href: "#", letter: "O"} O
      %a.letter_item{href: "#", letter: "P"} P
      %a.letter_item{href: "#", letter: "Q"} Q
      %a.letter_item{href: "#", letter: "R"} R
      %a.letter_item{href: "#", letter: "S"} S
      %a.letter_item{href: "#", letter: "T"} T
      %a.letter_item{href: "#", letter: "U"} U
      %a.letter_item{href: "#", letter: "V"} V
      %a.letter_item{href: "#", letter: "W"} W
      %a.letter_item{href: "#", letter: "X"} X
      %a.letter_item{href: "#", letter: "Y"} Y
      %a.letter_item{href: "#", letter: "Z"} Z

.row
  .col-md-12
    #grid
      =render partial: 'grid'
      

      

app/views/contacts/index.js.erb
$('#contact_form_modal').modal('hide');
$('#grid').html("<%= j (render 'grid') %>");


$('#masonry-container').masonry({
  itemSelector: '.box',
  isAnimated: !Modernizr.csstransitions, 
  columnWidth: function( containerWidth ) {
    return containerWidth / 6;
  }
}); 

app/views/contacts/new.js.erb
  $('#contact_form_modal').modal();
  $('#contact_form_modal').html("<%= j (render 'form') %>");

app/views/contacts/update.js.erb
<% if @contact != nil %>
  <% p @contact.inspect %>
  $('#contact_form_modal').html("<%= j (render 'form') %>");
<% else %>
  $('#contact_form_modal').modal('hide');
  $('#grid').html("<%= j (render 'grid') %>");
  
  $('#masonry-container').masonry({
    itemSelector: '.box',
    isAnimated: !Modernizr.csstransitions, 
    columnWidth: function( containerWidth ) {
      return containerWidth / 6;
    }
  }); 
  
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AddressBook
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default.navbar-fixed-top
      .container-fluid
        .navbar-header
          %button(type= "button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false")
            %span.sr-only Toggle navigation
            %span.icon-bar 
            %span.icon-bar  
            %span.icon-bar 
          %a.navbar-brand{href: "#{contacts_path}"} Contacts 
        - if current_user != nil
          .collapse.navbar-collapse 
            %ul.nav.navbar-nav
              %li.active
                = link_to 'New Contact', new_contact_path, remote: true 
              %li
                %a{href: "#"} Debug 
              %form{action: "#{contacts_path}"}(class="navbar-form navbar-left" role="search")
                .form-group
                  %input(type="text" name="query" class="form-control" placeholder="Search") 
                %button(type="submit" class="btn btn-default")Submit 
            %ul.nav.navbar-nav.navbar-right
              %li 
                %a{href: "#{destroy_user_session_path}"}(data-method='delete')
                  Log Out
                  %span.glyphicon.glyphicon-log-out(aria-hidden="true")
         
    
    .container
      = yield
    
      

#contact_form_modal.modal.fade 
  
        